# Staff Management API HTTP Requests

### 1. Get All Staff (Detail)
GET http://localhost:5077/api/staff

### 2. Get Staff by Name
GET http://localhost:5077/api/staff/search?keyword=john

### 3. Get Staff by ID
GET http://localhost:5077/api/staff/1

### 4. Add New Staff
POST http://localhost:5077/api/staff/add
Content-Type: application/json

{
    "fullName": "John Doe",
    "nim": "22012345",
    "binusianId": "B1234567",
    "gender": "Male",
    "email": "johndoe@binus.ac.id",
    "phoneNumber": "08123456789",
    "activeSemester": 4,
    "binusianStatus": "Active",
    "nik": "3174091234560001",
    "dateOfBirth": "2002-05-14",
    "address": "Jl. Sudirman No.20, Jakarta",
    "npwp": "12.345.678.9-012.345",
    "bankAccountNumber": "1234567890",
    "bankBranch": "KCP Bina Nusantara",
    "accountHolderName": "John Doe",
    "parentGuardianName": "Jane Doe",
    "parentGuardianPhone": "08129876543",
    "emergencyContact": "081312345678",
    "emergencyRelation": "Sibling"
}

### Other example
POST http://localhost:5077/api/staff/add
Content-Type: application/json

{
    "fullName": "Haryo",
    "nim": "29082399",
    "binusianId": "B1234997",
    "gender": "Male",
    "email": "haryo@binus.ac.id",
    "phoneNumber": "08123456789",
    "activeSemester": 4,
    "binusianStatus": "Active",
    "nik": "3174091234560001",
    "dateOfBirth": "2002-05-14",
    "address": "Jl. Sudirman No.20, Jakarta",
    "npwp": "12.345.678.9-012.345",
    "bankAccountNumber": "1234567890",
    "bankBranch": "KCP Bina Nusantara",
    "accountHolderName": "Haryo",
    "parentGuardianName": "John Doe",
    "parentGuardianPhone": "08129876543",
    "emergencyContact": "081312345678",
    "emergencyRelation": "Sibling"
}

### 5. Update Staff Data
PUT http://localhost:5077/api/staff/edit/4
Content-Type: application/json

{
    "FullName": "John Doe",
    "Email": "johndoe@binus.ac.id",
    "PhoneNumber": "08123456789",
    "Address": "Jl. Sudirman No.20, Jakarta",
    "NPWP": "12.345.678.9-012.345",
    "BankAccountNumber": "1234567890",
    "BankBranch": "KCP Bina Nusantara",
    "AccountHolderName": "John Doe",
    "EmergencyContact": "081312345678",
    "EmergencyRelation": "Sibling"
}

### 6. Delete Staff 
DELETE http://localhost:5077/api/staff/delete/2

### 7. Terminate Staff
POST http://localhost:5077/api/staff/terminate/5

### 8. Upload Excel File
POST http://localhost:5077/api/staff/upload/excel
Content-Type: multipart/form-data

< ./path/to/staff_list.xlsx

### 9. Upload Staff Photo
POST http://localhost:5077/api/staff/upload/photo/1
Content-Type: multipart/form-data

< ./path/to/photo.jpg
